export const agents = [
    {
        id: 1,
        name: 'Alex Johnson',
        role: 'Full Stack Developer',
        skills: ['React', 'Node.js', 'MongoDB', 'AWS'],
        hourlyRate: 85,
        rating: 4.9,
        reviews: 124,
        location: 'New York, USA',
        image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
        bio: 'Senior Full Stack Developer with 8+ years of experience building scalable web applications. Expert in React and Node.js ecosystems.',
    },
    {
        id: 2,
        name: 'Sarah Williams',
        role: 'UI/UX Designer',
        skills: ['Figma', 'Adobe XD', 'Prototyping', 'User Research'],
        hourlyRate: 95,
        rating: 5.0,
        reviews: 89,
        location: 'London, UK',
        image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
        bio: 'Award-winning UI/UX designer passionate about creating intuitive and beautiful user experiences.',
    },
    {
        id: 3,
        name: 'Michael Chen',
        role: 'DevOps Engineer',
        skills: ['Docker', 'Kubernetes', 'CI/CD', 'Terraform'],
        hourlyRate: 110,
        rating: 4.8,
        reviews: 56,
        location: 'San Francisco, USA',
        image: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
        bio: 'DevOps specialist focused on automation and infrastructure as code. Helping teams deploy faster and more reliably.',
    },
    {
        id: 4,
        name: 'Emily Davis',
        role: 'Mobile Developer',
        skills: ['React Native', 'iOS', 'Android', 'Swift'],
        hourlyRate: 90,
        rating: 4.9,
        reviews: 72,
        location: 'Toronto, Canada',
        image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
        bio: 'Mobile app developer with a track record of publishing 5-star apps on both App Store and Play Store.',
    },
    {
    id: 5,
    name: 'Rahul Mehta',
    role: 'Data Scientist',
    skills: ['Python', 'Machine Learning', 'Pandas', 'TensorFlow'],
    hourlyRate: 110,
    rating: 4.8,
    reviews: 54,
    location: 'Pune, India',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    bio: 'Data scientist specializing in predictive analytics and data-driven business insights.'
},
{
    id: 6,
    name: 'Olivia Chen',
    role: 'AI Engineer',
    skills: ['Deep Learning', 'NLP', 'PyTorch', 'LLMs'],
    hourlyRate: 130,
    rating: 4.9,
    reviews: 61,
    location: 'Singapore',
    image: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    bio: 'AI engineer building intelligent systems using large language models and deep learning.'
},
{
    id: 7,
    name: 'Ethan Walker',
    role: 'QA Automation Engineer',
    skills: ['Selenium', 'Cypress', 'Playwright', 'Test Automation'],
    hourlyRate: 70,
    rating: 4.6,
    reviews: 47,
    location: 'Austin, USA',
    image: 'https://images.unsplash.com/photo-1545996124-0501ebae84d0?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    bio: 'Quality assurance engineer focused on reliable automation testing for web applications.'
},
{
    id: 8,
    name: 'Ananya Gupta',
    role: 'Cybersecurity Analyst',
    skills: ['Penetration Testing', 'Network Security', 'SIEM', 'Risk Analysis'],
    hourlyRate: 120,
    rating: 4.7,
    reviews: 39,
    location: 'Gurgaon, India',
    image: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    bio: 'Cybersecurity analyst helping organizations protect systems against modern threats.'
},
{
    id: 9,
    name: 'Lucas Martin',
    role: 'Product Manager',
    skills: ['Product Strategy', 'Roadmapping', 'Agile', 'Stakeholder Management'],
    hourlyRate: 105,
    rating: 4.8,
    reviews: 52,
    location: 'Paris, France',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    bio: 'Product manager experienced in leading cross-functional teams to build impactful products.'
},
{
    id: 10,
    name: 'Sara Williams',
    role: 'Digital Marketing Specialist',
    skills: ['SEO', 'Content Marketing', 'Google Ads', 'Analytics'],
    hourlyRate: 60,
    rating: 4.5,
    reviews: 44,
    location: 'London, UK',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    bio: 'Marketing specialist driving online growth through data-backed digital strategies.'
},
{
    id: 11,
    name: 'Kenji Tanaka',
    role: 'Game Developer',
    skills: ['Unity', 'C#', 'Game Physics', 'AR/VR'],
    hourlyRate: 95,
    rating: 4.7,
    reviews: 36,
    location: 'Tokyo, Japan',
    image: 'https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    bio: 'Game developer creating immersive gaming experiences across mobile and desktop platforms.'
},
{
    id: 12,
    name: 'Victor Ivanov',
    role: 'Blockchain Developer',
    skills: ['Solidity', 'Ethereum', 'Smart Contracts', 'Web3'],
    hourlyRate: 140,
    rating: 4.8,
    reviews: 41,
    location: 'Kyiv, Ukraine',
    image: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    bio: 'Blockchain developer building secure decentralized applications and smart contracts.'
},
{
    id: 13,
    name: 'Maria Lopez',
    role: 'Technical Support Engineer',
    skills: ['Customer Support', 'Troubleshooting', 'SaaS', 'CRM'],
    hourlyRate: 50,
    rating: 4.6,
    reviews: 59,
    location: 'Mexico City, Mexico',
    image: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    bio: 'Technical support engineer ensuring smooth customer experience and quick issue resolution.'
},
{
    id: 14,
    name: 'Ahmed Hassan',
    role: 'Cloud Architect',
    skills: ['AWS', 'Azure', 'Cloud Security', 'Microservices'],
    hourlyRate: 150,
    rating: 4.9,
    reviews: 46,
    location: 'Dubai, UAE',
    image: 'https://images.unsplash.com/photo-1542206395-9feb3edaa68d?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    bio: 'Cloud architect designing scalable, secure, and cost-optimized cloud infrastructures.'
}
];
